/** Short definitions for official two-letter Scrabble words, used if the live lookup misses. */
export const TWO_LETTER_DEFINITIONS: Record<string, string> = {
  AA: 'Rough, cindery lava.',
  AB: 'An abdominal muscle.',
  AD: 'An advertisement.',
  AE: 'One (Scottish).',
  AG: 'Agriculture.',
  AH: 'To exclaim in delight or surprise.',
  AI: 'A three-toed sloth.',
  AL: 'An East Indian tree.',
  AM: 'Present tense of be.',
  AN: 'An indefinite article.',
  AR: 'The letter R.',
  AS: 'To the same degree.',
  AT: 'In or near the position of.',
  AW: 'Used to express dismay or sympathy.',
  AX: 'A chopping tool.',
  AY: 'An affirmative vote.',
  BA: 'The eternal soul, in Egyptian religion.',
  BE: 'To exist.',
  BI: 'Bisexual.',
  BO: 'A pal; a fellow.',
  BY: 'Near; aside.',
  DA: 'A father; dad.',
  DE: 'Of; from (used in names).',
  DO: 'The first tone of the diatonic scale.',
  ED: 'Education.',
  EF: 'The letter F.',
  EH: 'Used to express doubt or to ask for repetition.',
  EL: 'An elevated railroad.',
  EM: 'The letter M.',
  EN: 'The letter N.',
  ER: 'Used to express hesitation.',
  ES: 'The letter S.',
  ET: 'Past tense of eat.',
  EW: 'Used to express disgust.',
  EX: 'The letter X; a former spouse.',
  FA: 'The fourth tone of the diatonic scale.',
  FE: 'A Hebrew letter.',
  GI: 'A judo or karate garment.',
  GO: 'To leave or move.',
  HA: 'Used to express surprise or triumph.',
  HE: 'A male person or animal.',
  HI: 'A greeting.',
  HM: 'Used to express thought or doubt.',
  HO: 'Used to attract attention.',
  ID: 'A part of the psyche.',
  IF: 'On the condition that.',
  IN: 'To harvest; a place one is located.',
  IS: 'Present tense of be.',
  IT: 'A thing previously mentioned.',
  JO: 'A sweetheart.',
  KA: 'The spiritual self, in Egyptian religion.',
  KI: 'Vital energy; a variant of qi.',
  LA: 'The sixth tone of the diatonic scale.',
  LI: 'A Chinese unit of distance.',
  LO: 'Look; behold.',
  MA: 'Mother.',
  ME: 'The objective case of I.',
  MI: 'The third tone of the diatonic scale.',
  MM: 'Used to express satisfaction.',
  MO: 'A moment.',
  MU: 'A Greek letter.',
  MY: 'Belonging to me.',
  NA: 'No; not.',
  NE: 'Born with the name of.',
  NO: 'A negative reply.',
  NU: 'A Greek letter.',
  OD: 'A hypothetical force of natural power.',
  OE: 'A whirlwind off the Faroe Islands; a small island.',
  OF: 'Coming from; belonging to.',
  OH: 'To exclaim in surprise or pain.',
  OI: 'Used to attract attention or express dismay.',
  OK: 'To approve.',
  OM: 'A mantra used in meditation.',
  ON: 'In contact with; to go forward.',
  OP: 'A style of abstract art.',
  OR: 'A conjunction; heraldic gold.',
  OS: 'A bone.',
  OW: 'Used to express pain.',
  OX: 'A bovine animal; a clumsy person.',
  OY: 'Used to express dismay.',
  PA: 'Father.',
  PE: 'A Hebrew letter.',
  PI: 'A Greek letter.',
  PO: 'A chamber pot.',
  QI: 'The vital force in Chinese philosophy.',
  RE: 'The second tone of the diatonic scale.',
  SH: 'Used to urge silence.',
  SI: 'The seventh tone of the diatonic scale.',
  SO: 'In the way or manner shown.',
  TA: 'An expression of thanks.',
  TE: 'The seventh tone of the diatonic scale.',
  TI: 'The seventh tone of the diatonic scale.',
  TO: 'In the direction of.',
  UH: 'Used to express hesitation.',
  UM: 'Used to express hesitation.',
  UN: 'One (dialect).',
  UP: 'To raise; toward a higher place.',
  US: 'The objective case of we.',
  UT: 'A syllable representing a musical tone.',
  WE: 'The nominative plural of I.',
  WO: 'Woe; misery.',
  XI: 'A Greek letter.',
  XU: 'A former Vietnamese coin.',
  YA: 'You (dialect).',
  YE: 'You (archaic).',
  YO: 'Used to attract attention.',
  ZA: 'A pizza.',
}
